version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  feasibility:
    run: stata-mp:latest analysis/00_Test_runs_and_feasibility.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: analysis/logfiles/00_Test_runs_and_feasibility.log
        figure1: analysis/outfiles/00_negtests_by_week.gph
        figure2: analysis/outfiles/00_tpp_pos_by_week.gph

  run_all:
    needs: [feasibility]
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml