version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  feasibility:
    run: stata-mp:latest analysis/00_Test_runs_and_feasibility.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/00_Test_runs_and_feasibility.log
        figure1: output/00_spells.svg

  crMAIN:
    run: stata-mp:latest analysis/cr_analysis_dataset.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_analysis_dataset.log
      highly_sensitive:
        data: analysis/cr_analysis_dataset.dta

  anSTP:
    run: stata-mp:latest analysis/an_stp.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/an_stp.log

  anCASE:
    run: stata-mp:latest analysis/an_ccount_crude.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_ccount_crude.log
        figure1: output/tpp_sgss_counts.svg
        figure2: output/tpp_type_counts.svg
        figure3: output/tpp_fp.svg

  anCOX:
    run: stata-mp:latest analysis/an_cox_models.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_models.log
#        figure1: output/unadj_cox_haz.svg
        figure1: output/unadj_cox_month.svg
#        figure2: output/utla_haz.svg
        figure3: output/unadj_cox_week.svg
        figure4: output/unadj_cox_week_nl.svg
        figure5: output/utla_cox_month.svg
        figure6: output/unadj_sgss_month.svg
        figure7: output/unadj_sgss_week.svg
        figure8: output/unadj_sgss_week_nl.svg
