version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  feasibility:
    run: stata-mp:latest analysis/00_Test_runs_and_feasibility.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/00_Test_runs_and_feasibility.log
#        figure1: output/00_spells.svg

  crMAIN:
    run: stata-mp:latest analysis/cr_analysis_dataset.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_analysis_dataset.log
      highly_sensitive:
        data: analysis/cr_analysis_dataset.dta

  anCASE:
    run: stata-mp:latest analysis/an_ccount_crude.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_ccount_crude.log
        figure1: output/tpp_sgss_counts.svg
        figure2: output/tpp_type_counts.svg
        figure3: output/tpp_fp.svg

  run_all:
    needs: [feasibility]
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml